Check PHP8 + add Phpstan + some improvment
openfoodfacts/openfoodfacts-php pull request #35
Opened 2021-09-29 21:08 UTC by Benoit382

- Check compatibility with PHP8
- Update PHPunit
- Add (PHPSstan)[https://github.com/phpstan/phpstan]
- Add cs-fixer with local rule (feel free to update)
- Improve some test (too many copy paste)
- Say "What fucking code" and gitblame myself... 

Ready for all comment|blame ;)

2021-10-11 06:16 UTC, gherardobertini commented
Have you tried to add `php 8.0` in travis?  
I notice that I can't install the package because is stuck to `psr/log ^1.0`

2021-10-13 08:23 UTC, Dwarfex commented
You could merge the PR https://github.com/openfoodfacts/openfoodfacts-php/pull/32 into your branch, and check if the Github Actions will run successfull.

2021-10-13 08:44 UTC, Dwarfex requested changes
Let's disscuss the suggested changes if needed.

2021-10-13 08:44 UTC, Dwarfex commented on README.md
> +6. Create a new Pull Request
7. Check that all Tests in the PR run

2021-10-13 08:44 UTC, Dwarfex commented on composer.json
> +      "Tests\\": "tests/"
I would use a more distinct namespace than "Tests" - more like "OpenFoodFactsTests"

2021-10-13 08:44 UTC, Dwarfex commented on src/Collection.php
> +    private $pageSize       = 0;
I would suggest this:
```suggestion
    /** @var array<int, Document> */
    private array $listDocuments  = [];
    private int $count          = 0;
    private int $page           = 0;
    private int $skip           = 0;
    private int $pageSize       = 0;
```

2021-10-13 08:44 UTC, Dwarfex commented on src/Collection.php
>      public function key()
```suggestion
     */
    public function key(): ?int
```

2021-10-13 18:55 UTC, Benoit382 commented on src/Collection.php
> +    private $pageSize       = 0;
The typed properties is not compatible with PHP 7.1
https://stitcher.io/blog/typed-properties-in-php-74

2021-10-13 18:55 UTC, Benoit382 commented on src/Collection.php
>      public function key()
The typed properties is not compatible with PHP 7.1
https://stitcher.io/blog/typed-properties-in-php-74

2021-10-13 18:58 UTC, Benoit382 commented on README.md
> +6. Create a new Pull Request
Last time,  all test pass but today, some one didn't want to pass...
I think we should mock the openfoodfact response.

2021-10-13 19:00 UTC, Benoit382 commented
> Have you tried to add `php 8.0` in travis? I notice that I can't install the package because is stuck to `psr/log ^1.0`

I will check that.

2021-10-14 11:41 UTC, Benoit382 commented
I pick all code from #32

2021-10-14 14:20 UTC, Dwarfex commented on README.md
> +6. Create a new Pull Request
Yeah, that would be best. 
Testing the SKD and indirectly testing the API for correct behaviour is not best practice.

2021-10-14 14:24 UTC, Dwarfex approved these changes

2021-10-14 14:24 UTC, Dwarfex commented on src/Collection.php
> +    private $pageSize       = 0;
Ah - the fate of old code :D - we then might want to up the requirements to 7.3/7.4 (https://www.php.net/supported-versions.php) and add a new semantic release.

2021-10-15 11:32 UTC, Benoit382 commented
I think we should squash and merge, and create a new issues, with bump version + create Unit|Functional test and remove integration test

2021-10-20 08:13 UTC, Dwarfex commented
@Benoit382 that works for me :)

2021-10-26 21:25 UTC, Benoit382 commented
Some one can squash and merge ?

2021-10-28 16:01 UTC, merged