0.3.x dev
openfoodfacts/openfoodfacts-php pull request #47
Opened 2023-02-16 17:25 UTC by Dwarfex

### What
- 

### Screenshot

### Fixes bug(s)
- 

### Part of 
-

2023-02-16 21:31 UTC, khalyomede commented
This pull request will fix https://github.com/openfoodfacts/openfoodfacts-php/issues/45.

2024-01-14 16:31 UTC, teolemon commented
Can we merge?

2024-01-14 17:33 UTC, epalmans requested changes
all good to me, but I noticed tests failed due to a (seemingly unrelated?) problem with calls made out to  https://world.openfoodfacts.net/cgi/product_jqm2.pl : "Server error: `POST https://world.openfoodfacts.net/cgi/product_jqm2.pl` resulted in a `502 Bad Gateway` response".

Happens at calling https://github.com/openfoodfacts/openfoodfacts-php/blob/ef4eb31333286270b2d10e0e7393ecbf1ee15658/src/Api.php#L472 from:
- OpenFoodFactsTests\ApiFoodCacheTest::testApiAddProduct
- OpenFoodFactsTests\ApiFoodTest::testApiAddProduct

2024-03-11 17:25 UTC, scybulski commented
What's the status here? I've just run all the tests and they pass so the error might have been just a temporary api issue not related to this repository. And as a side note it's blocking a related package https://github.com/openfoodfacts/openfoodfacts-laravel/pull/43 from being updated to the recent Laravel,

2024-04-29 13:32 UTC, DonatasIk commented
This needs to be merged. It's creating a bottleneck for the related packages.

2024-04-29 14:45 UTC, Benoit382 approved these changes

2024-04-29 14:57 UTC, Benoit382 commented on src/Collection.php
> +        $this->count    = $data['count'] ?? null;
```suggestion
        $this->count    = $data['count'] ?? 0;
```
Error on this test

2024-04-29 15:01 UTC, Benoit382 commented
I launched the phpunit on my side, except this error : https://github.com/openfoodfacts/openfoodfacts-php/pull/47#discussion_r1583230170 all it's works
---
In this project, it's real difficult to update the code...

2024-05-01 07:23 UTC, teolemon commented
@epalmans you need to reapprove since you requested changes

2024-05-01 07:24 UTC, epalmans approved these changes

2024-05-01 07:29 UTC, epalmans commented
> @epalmans you need to reapprove since you requested changes

done.
Changed:
- suggested change from @Benoit382
- marked for skipping: the test that was failing due to api issues
- satisified cs-fixer/phpstan

After your review we may merge and tag it

2024-05-01 07:36 UTC, Benoit382 approved these changes

2024-05-01 08:05 UTC, teolemon approved these changes
Thank you all for getting this one through 🎉

2024-05-01 08:06 UTC, merged