Force user agent
openfoodfacts/openfoodfacts-php pull request #49
Opened 2023-08-22 13:37 UTC by Benoit382

### What
Force user agent and update some dependencies

### Issues
#48

2023-08-23 17:07 UTC, Dwarfex requested changes
This PR does a lot of things - besides adding a User Agent - and it breaks semantic versionig -> would result in the need of a new major version vor the library.

2023-08-23 17:07 UTC, Dwarfex commented on .github/workflows/ci.yml
> +        php: ['8.1', '8.2']
I would suggest not activly dropping support of Php 8.0 as it is still maintained and i would see this as a long living library.

2023-08-23 17:07 UTC, Dwarfex commented on src/Api.php
> +        public readonly string $userAgent,
you are breaking semantic versioning by adding this parameter in the front. 

We should aswell set a valuable default here, if we intend to use it.

2023-08-23 17:07 UTC, Dwarfex commented on src/Api.php
> +                ]
I'd suggest setting up the clients default headers within the constructor - and not for each individual call

2023-08-23 17:07 UTC, Dwarfex commented on src/Api.php
> +        /** @var array $jsonResult */
json_decode returns "mixed" not "array" - this is a wrong typehint

2023-08-23 17:07 UTC, Dwarfex commented on src/Api.php
> +        /** @var array $jsonResult */
here aswell

2023-08-23 17:07 UTC, Dwarfex commented on src/Api.php
> +                  $parameters ?? ''
Isn't this null check useless as you verify in L498-500 for a given string?

2023-08-23 17:07 UTC, Dwarfex commented on src/Api.php
> +                  $resourceType ?? ''
```suggestion
                  $resourceType
```

2023-08-23 17:07 UTC, Dwarfex commented on src/Api.php
> +                  $resourceType ?? ''
```suggestion
                  $resourceType
```

2023-08-23 17:07 UTC, Dwarfex commented on src/Api.php
> +                    is_array($parameters) ? '' : $parameters
What is your intention here ? - Removing the parameters if they are an array? - Why?

2023-08-23 17:07 UTC, Dwarfex commented on src/Api.php
> +     */
```suggestion
```

2023-08-23 17:07 UTC, Dwarfex commented on src/Api.php
> +            'headers' => $this->getDefaultHeaders(),
```suggestion
            'headers' => ['User-Agent' => 'SDK PHP - ' . $this->userAgent],
```

2023-08-23 17:07 UTC, Dwarfex commented on src/Api.php
> +
```suggestion
```

2023-08-23 17:07 UTC, Dwarfex commented on src/Collection.php
> +        next($this->listDocuments);
This looks right - but changes the interface for anyone using it.

2023-08-23 17:07 UTC, Dwarfex commented on src/Document.php
> +    public function __construct(array $data)
This is version breaking

2023-08-23 17:07 UTC, Dwarfex commented on tests/ApiFoodCacheTest.php
>          ]);
Why not using the newly added user-agent here?

2023-08-23 17:07 UTC, Dwarfex commented on tests/FilesystemTrait.php
> +    public static function recursiveDeleteDirectory(string $dir): void
again version breaking - and as this is a trait -> tests subfolder is the wrong location

2023-08-23 17:07 UTC, Dwarfex commented on tests/FilesystemTrait.php
> +    }
Why is this test related function in a generic trait?

2024-05-01 08:58 UTC, teolemon commented
@Benoit382 merge conflicts

2024-05-01 10:09 UTC, closed without merging

2024-05-01 10:14 UTC, Benoit382 commented
Oups, i removed it :stuck_out_tongue: 
I will rework on it soon